---
- name: Configure Redis Server
  hosts: redis_servers
  become: yes
  vars:
    ansible_user: "rocky"
  roles:
    - redis

- name: Configure Frontend Server
  hosts: frontend_servers
  become: yes
  vars:
    ansible_user: "ubuntu"
  roles:
    - frontend
